#!/bin/sh

set -e

if ! [ $# -eq 1 ]; then
    echo "Usage: run_java <java.file>"
    exit 1
fi

PACKAGE=$(grep -E '^package ([a-z]*.)+[a-z]*;.*$' "$1" | sed -E 's/^package (.*);.*$/\1/')

while [ "$(find . -maxdepth 1 -name pom.xml -o -name .git | wc -l)" -eq 0 ]
do 
    if [ "$PWD" = "$HOME" ]; then
        echo No maven project found
        exit 1
    fi
    cd ..
done

echo "$PWD"

mvn compile
echo
mvn exec:java -Dexec.mainClass="$PACKAGE.Main" -q

