# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-2e95fab5-a37f-4d91-8cea-308c3c6400c3";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-2e95fab5-a37f-4d91-8cea-308c3c6400c3".device = "/dev/disk/by-uuid/2e95fab5-a37f-4d91-8cea-308c3c6400c3";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5BE1-59DC";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-a3c7704c-a66f-43f5-b95a-1423f81ceb60"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
